version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/python:3.9.1


    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Pipfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: pipenv sync --dev

      - save_cache:
          paths:
            - ~/.local
            - ~/.cache
          key: v1-dependencies-{{ checksum "Pipfile.lock" }}

      # - run:
      #     name: run tests
      #     command: |
      #       pipenv shell
      #       cd pollsapi
      #       python manage.py test

      - store_artifacts:
          path: test-reports
          destination: test-reports